// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"` //刷新后的token
}

type UserDetailRequest struct {
	Identity string `json:"identity"`
}

type UserDetailResponse struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type SendCodeRequest struct {
	Email string `json:"email"`
}

type SendCodeResponse struct {
}

type UserRegisterRequest struct {
	Name     string `json:"name"`     //用户名
	Password string `json:"password"` //密码
	Email    string `json:"email"`
	Code     string `json:"code"` //邮箱验证码
}

type UserRegisterResponse struct {
}

type FileUploadRequest struct {
	Hash string `json:"hash,optional"`
	Name string `json:"name,optional"`
	Ext  string `json:"ext,optional"`
	Size int64  `json:"size,optional"`
	Path string `json:"path,optional"`
}

type FileUploadResponse struct {
	Identity string `json:"identity"`
	Ext      string `json:"ext"`
	Name     string `json:"name"`
}

type UserRepositoryRelationRequest struct {
	ParentId           int64  `json:"parent_id"` //记录父文件ID
	RepositoryIdentity string `json:"repository_identity"`
	Ext                string `json:"ext"`
	Name               string `json:"name"`
}

type UserRepositoryRelationResponse struct {
}

type UserFileListRequest struct {
	Identity string `json:"identity,optional"`
	Page     int    `json:"page,optional"`
	Size     int    `json:"size,optional"`
}

type UserFileListResponse struct {
	List  []*UserFile `json:"list"` //用户文件信息的切片
	Count int64       `json:"count"`
}

type UserFile struct {
	Id                 int64  `json:"id"`
	Identity           string `json:"identity"`
	RepositoryIdentity string `json:"repository_identity"`
	Name               string `json:"name"`
	Ext                string `json:"ext"`
	Path               string `json:"path"`
	Size               int64  `json:"size"`
}

type UserFileNameChangeRequest struct {
	Identity string `json:"identity"`
	Name     string `json:"name"`
}

type UserFileNameChangeResponse struct {
}

type UserFolderCreateRequest struct {
	ParentId int64  `json:"parent_id"`
	Name     string `json:"name"`
}

type UserFolderCreateResponse struct {
	Identity string `json:"identity"`
}

type UserFileDeleteRequest struct {
	Identity string `json:"identity"`
}

type UserFileDeleteResponse struct {
}

type UserFileMoveRequest struct {
	Idnetity       string `json:"identity"`
	ParentIdnetity string `json:"parent_identity"`
}

type UserFileMoveResponse struct {
}

type UserShareCreateRequest struct {
	UserRepositoryIdentity string `json:"user_repository_identity"`
	ExpiredTime            int    `json:"expired_time"`
}

type UserShareCreateResponse struct {
	Identity string `json:"identity"`
}

type ShareBasicDetailRequest struct {
	Identity string `json:"identity,optional"`
}

type ShareBasicDetailResponse struct {
	RepositoryIdentity string `json:"repository_identity"` //资源文件identity
	Name               string `json:"name"`
	Ext                string `json:"ext"`
	Size               int64  `json:"size"`
	Path               string `json:"path"`
}

type UserShareSaveRequest struct {
	RepositoryIdentity string `json:"repository_identity"`
	ParentId           int64  `json:"parent_id"` //父级目录id
}

type UserShareSaveResponse struct {
	Identity string `json:"identity"` //用户文件关联表identity
}

type RefreshTokenRequest struct {
}

type RefreshTokenResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type FileUploadQuickRequest struct {
	Md5      string `json:"md5"` //文件的md5值
	Name     string `json:"name"`
	Ext      string `json:"ext"`
	ParentId int64  `json:"parent_id"` //父级目录id
}

type FileUploadQuickResponse struct {
	Identity string `json:"identity"` //文件的repository_pool的id
	UploadId string `json:"upload_id"`
	Key      string `json:"key"`
}

type FileUploadChunkRequest struct {
}

type FileUploadChunkResponse struct {
	Etag string `json:"etag"` // MD5
}

type FileUploadChunkCompleteRequest struct {
	Md5        string      `json:"md5"`
	Name       string      `json:"name"`
	Ext        string      `json:"ext"`
	Size       int64       `json:"size"`
	ParentId   int64       `json:"parent_id"` //父级目录id
	Key        string      `json:"key"`
	UploadId   string      `json:"upload_id"`
	CosObjects []CosObject `json:"cos_objects"` //每个分块文件的校验结构
}

type CosObject struct {
	PartNumber int    `json:"part_number"`
	Etag       string `json:"etag"`
}

type FileUploadChunkCompleteResponse struct {
	Identity string `json:"identity"` // 用户中新文件存储池identity
}

type FileDownloadRequest struct {
	Identity string `json:"identity"` //文件的identity
}

type FileDownloadResponse struct {
	FileDir string `json:"file_dir"` //文件本地路径
}
